name: CI/CD
on:
  push:
    branches:
      main
  pull_request:
    branches: ['main', 'develop']

jobs:
    TestingCodeSyntax:
        runs-on: ubuntu-latest
        steps:
        - name: Clone code repository
          uses: actions/checkout@v2
        - name: Installing Node
          uses: actions/setup-node@v2
          with:
              node-version: "16"
        - name: Installing dependencies
          run:  npm install

        - name: Run EsLint
          run: npm run lint

    TestApplicationFunctionality:
      runs-on: ubuntu-latest
      needs: TestingCodeSyntax
      if: always()
      steps:
        - name: Clone code repository
          uses: actions/checkout@v2
        - name: Installing Node
          uses: actions/setup-node@v2
          with:
            node-version: "16"

        - name: Installing dependencies
          run: npm install

        - name: Installing Cypress
          run: npx cypress install

        - name: Run Cypress Tests
          run:  npm run test

        - name: Setup Chrome for Selenium
          run: sudo apt-get install -y chromium-browser

        - name: Executing Selenium Tests
          run: npm run test:selenium

    DeployChanges:
      runs-on: ubuntu-latest
      needs: TestApplicationFunctionality
      if: success()

      steps:
        - name: Clone code repository
          uses: actions/checkout@v2
        - name: Installing Node
          uses: actions/setup-node@v2
          with:
            node-version: "16"

        - name: Installing dependencies
          run: npm install

        - name: Build Project
          run:  npm run generate

        - name: Install Vercel CLI
          run: npm install -g vercel

        - name: Deploy to Vercel
          run:  vercel --token ${{ secrets.VERCEL_DEPLOY_TOKEN }} --prod














