name: CI/CD
on: push 

jobs:
    TestingSyntax:
        runs-on: ubuntu-latest
        steps:
        - name: Clone code repository
          uses: actions/checkout@v2
        - name: Installing Node
          uses: actions/setup-node@v2
          with:
              node-version: "16"
        - name: Installing dependencies
          run:  npm install

        - name: Run EsLint
          run: npm run lint


          
          

        
    

 
